# Generated by Django 4.0 on 2023-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_book_image_alter_book_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Humanities', 'Humanities')], default='Engineering', max_length=15),
        ),
    ]
