# Generated by Django 4.0 on 2023-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_book_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Humanities', 'Humanities'), ('Commerce', 'Commerce'), ('Medical', 'Medical')], default='Engineering', max_length=15),
        ),
    ]
