# Generated by Django 4.0 on 2023-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_book_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Humanities', 'Humanities'), ('Commerce', 'Commerce')], default='Engineering', max_length=15),
        ),
    ]
