# Generated by Django 4.0 on 2023-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
    ]
